version: '3'
services:
  image_text_conversion:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/home/sasha/Pictures:/app/screenshots:rw"
      - "/home/sasha/Code/studies/Cources/aws/cloud-practitioner-CLF-C01-CLF-C02/output_text:/app/output_text:rw"
    user: "1000:1000"