version: '3'
services:
  image_text_conversion:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/home/sasha/Pictures/screenshot:/app/screenshots:rw"
      - "/tmp:/app/output_text:rw"
    user: "1000:1000"
