version: '3'
services:
  image_text_conversion:
    image: pic2text
    volumes:
      - "YOUR/INPUT/PIC/DIRECTORY/PATH:/app/screenshots:rw"
      - "YOUR/OUTPUT/DIRECTORY/PATH:/app/output_text:rw"
    user: "1000:1000"