version: '3'
services:
  image_text_conversion:
    image: pic2text
    volumes:
      - "/home/sasha/code/studies/aws/cloud-practitioner-CLF-C01-CLF-C02/screenshots:/app/screenshots"
      - "/home/sasha/code/studies/aws/cloud-practitioner-CLF-C01-CLF-C02/output_text:/app/output_text"
